/* Generated from locales/ja.json by scripts/build-japanese.py. */
window.TWO_D_ONE_JA = {
  "Skip to content": "本文へ移動",
  "Familiar characters": "身近なものに、らしさを。",
  "Get in touch": "お問い合わせ",
  "More about us": "2D1について",
  "Studio": "スタジオ",
  "Clear ideas, with character.": "明確なアイデアに、個性を。",
  "Design Consulting": "デザインコンサルティング",
  "Advisory, Direction": "アドバイザリー、ディレクション",
  "Brand Design": "ブランドデザイン",
  "Strategy, Visual Identity": "戦略、ビジュアルアイデンティティ",
  "Digital Product Design": "デジタルプロダクトデザイン",
  "Website, UX/UI, Design System": "ウェブサイト、UX/UI、デザインシステム",
  "Shop": "ショップ",
  "Notify me when it’s out": "発売のお知らせを受け取る",
  "Community": "コミュニティ",
  "Relationship Advice": "恋愛・パートナーシップの相談",
  "Enter profile": "プロフィールを入力",
  "Connect": "つながる",
  "Your email address": "メールアドレス",
  "Sign up": "登録する",
  "Close": "閉じる",
  "A little about you.": "あなたのことを、少し。",
  "Name": "お名前",
  "Email": "メールアドレス",
  "Age": "年齢",
  "Optional": "任意",
  "City / time zone": "お住まいの都市・タイムゾーン",
  "A little about your situation": "現在の状況について",
  "What would you like to talk about?": "どんなことを話したいですか？",
  "What would you like to get out of the session?": "この時間を通じて、どんなことを得たいですか？",
  "Send profile": "プロフィールを送信",
  "About": "2D1について",
  "Why familiar things matter": "身近なものが、大切になる理由",
  "favorite something": "お気に入り",
  "Character creates the connection": "らしさが、つながりを生む",
  "life happens around them": "そのそばで日々が積み重なっていくから",
  "Reductionist, with wit": "そぎ落として、ひとさじの遊び心を。",
  "The House of Familiar Things": "身近なものたちの家",
  "Continue reading": "続きを読む",
  "Say hello.": "こんにちは。",
  "Full name": "お名前",
  "Company": "会社名",
  "Category": "お問い合わせの種類",
  "New Business": "お仕事のご相談",
  "Media Inquiry": "取材・メディアのお問い合わせ",
  "Other": "その他",
  "Message": "メッセージ",
  "Website": "ウェブサイト",
  "Send": "送信する",
  "Thank you": "ありがとうございます",
  "our Notion form": "Notionのお問い合わせフォーム",
  "(opens in a new tab)": "（新しいタブで開きます）",
  "instead.": "をご利用ください。",
  ".": "。",
  "Introduction": "はじめに",
  "Social media": "ソーシャルメディア",
  "2D1, back to top": "2D1、ページの先頭へ",
  "2D1, home": "2D1、ホームへ",
  "Click to pause or resume": "クリックで一時停止・再開",
  "Selected design work. Scroll to browse; press Space to pause or resume motion.": "制作事例。横にスクロールしてご覧ください。スペースキーで動きを一時停止・再開できます。",
  "For example, whether you’re single, dating, or in a relationship.": "例：現在は独身、デート中、パートナーがいるなど。",
  "Black canvas 2D1 tote with a red strap lining and square tag": "赤いストラップの裏地と四角いタグがついた、2D1の黒いキャンバストート",
  "Black canvas tote with subtle charcoal pixel eyes on the front, a small 2D1 logo on the back, red strap lining, and a square red tag.": "前面に控えめなチャコールグレーのピクセルアイ、背面に小さな2D1ロゴ、赤いストラップの裏地と四角い赤タグを配した黒いキャンバストート。",
  "2D1 tote. Hover over the bag to see inside; tap or press Enter to toggle X-ray.": "2D1のトート。バッグにカーソルを重ねると中が見えます。タップまたはEnterキーで透視表示を切り替えられます。",
  "Aviator identity against a purple sky": "紫の空を背景にしたAviatorのブランドアイデンティティ",
  "Aviator website design": "Aviatorのウェブサイト",
  "Aviator identity on a water bottle": "ボトルに展開したAviatorのロゴ",
  "Aviator embroidered cap": "Aviatorの刺繍入りキャップ",
  "DeepDrip wordmark": "DeepDripのワードマーク",
  "DeepDrip website design": "DeepDripのウェブサイト",
  "DeepDrip stickers on a laptop": "ノートパソコンに貼ったDeepDripのステッカー",
  "Supateam event identity": "Supateamのイベントアイデンティティ",
  "Supateam digital product": "Supateamのデジタルプロダクト",
  "Supateam event badge": "Supateamのイベントバッジ",
  "Supateam business cards": "Supateamの名刺",
  "Email signup isn’t connected yet. Nothing is sent or saved here.": "メール登録はまだ準備中です。入力内容は送信・保存されません。",
  "Signup isn’t connected yet. Your email was not sent or saved.": "メール登録はまだ準備中です。メールアドレスは送信・保存されていません。",
  "Profile submission isn’t connected yet. Nothing was sent or saved.": "プロフィールの受付はまだ準備中です。入力内容は送信・保存されていません。",
  "This form isn’t connected yet. Nothing you enter is sent or saved.": "このフォームはまだ準備中です。入力内容は送信・保存されません。",
  "This form isn’t connected yet. Nothing you enter is sent or saved. Fields marked with a red square are required.": "このフォームはまだ準備中です。入力内容は送信・保存されません。赤い四角のついた項目は必須です。",
  "Tell me where you’re at, what’s on your mind, and what you’d like from our conversation.": "今のあなたのこと、気になっていること、この会話で得たいことを教えてください。",
  "Tell us a little about you and what you have in mind.": "あなたのことや、考えていることを少し教えてください。",
  "Your message is in. We’ll get back to you within five business days.": "メッセージを受け取りました。5営業日以内にお返事します。",
  "Our form isn’t connected yet, so nothing was sent. You can reach us through": "このフォームはまだ準備中のため、送信されていません。お問い合わせは",
  "Please check your email address.": "メールアドレスをご確認ください。",
  "Please choose a category.": "お問い合わせの種類を選んでください。",
  "Please fill in this required field.": "この項目を入力してください。",
  "Sending": "送信中",
  "One moment…": "しばらくお待ちください。",
  "Nothing was sent.": "送信されていません。",
  "The form is temporarily unavailable. Please try again later.": "現在フォームをご利用いただけません。時間をおいてお試しください。",
  "A few too many messages. Please wait a moment and try again.": "送信が続いています。少し待ってからお試しください。",
  "Something in the form needs another look. Please check your details.": "入力内容をご確認ください。",
  "We couldn’t send your message. Please try again in a moment.": "メッセージを送信できませんでした。時間をおいてお試しください。",
  "We couldn’t confirm your message was received. Please try again.": "メッセージの受信を確認できませんでした。もう一度お試しください。",
  "That took a little too long. Please try again.": "時間がかかりすぎているようです。もう一度お試しください。",
  "We couldn’t connect. Please try again in a moment.": "接続できませんでした。時間をおいてお試しください。",
  "2D1 — Independent design studio. Familiar Characters.": "2D1 — 独立系デザインスタジオ。身近なものに、らしさを。",
  "About — 2D1": "2D1について",
  "About 2D1": "2D1について",
  "2D1 is an independent design studio with a shop of its own. About the studio, and why familiar things matter.": "2D1は、自分たちのショップも持つ独立系デザインスタジオ。私たちのこと、そして身近なものが大切になる理由について。",
  "Branding, digital products, and a point of view on everyday design. Familiar Characters.": "ブランディング、デジタルプロダクト、そして日常のデザインへのまなざし。身近なものに、らしさを。",
  "The 2D1 logo in white on red.": "赤い背景に白い2D1のロゴ。",
  "Familiar Characters": "身近なものに、らしさを。",
  "An independent design studio working in branding and digital products, and an editorial home for Familiar Characters.": "ブランディングとデジタルプロダクトに取り組み、身近なものの「らしさ」を考える独立系デザインスタジオ。",
  "2D1 is an independent design studio. We work by editing until the idea is clear, then keeping the one detail that makes you smile.": "2D1は、独立系のデザインスタジオです。アイデアが明快になるまでそぎ落とし、最後に、思わず笑顔になるひと工夫を残します。",
  "We also make our own stuff and connect with those who need a pair of ears.": "自分たちでものをつくること。そして、誰かに話を聞いてほしい人と、つながることも。",
  "We work with founders, small teams, and independent businesses to make their ideas clear and give them a character of their own. Sometimes that means building a brand from the beginning. Sometimes it means rethinking a website, refining a product, or finding a better way to tell an existing story. From strategy and visual identity to the details of a digital experience, we bring a fresh pair of eyes and a hands-on approach. The aim is work that feels like you, makes sense to the people who use it, and is easy to live with.": "創業者や少人数のチーム、小さな事業とともに、アイデアを明快にし、その人たちらしいかたちにしていきます。ブランドをゼロからつくることもあれば、ウェブサイトを見直したり、プロダクトを磨いたり、今ある物語の伝え方を考え直したりすることも。戦略やビジュアルアイデンティティから、デジタル体験の細部まで。新しい視点で向き合い、手を動かしながら、一緒につくります。目指すのは、あなたらしく、使う人にきちんと伝わり、日々に自然となじむデザインです。",
  "Character 01 is our first everyday object: a canvas tote made to find a place in your routine. A familiar shape, a long strap, and a flash of red where you might not expect it. We’re working through the details, from how it sits on your shoulder to where the small things go inside. Like the work we do for others, it starts with a clear idea and keeps the detail that makes it its own. The bag is still in development. If you’d like to see it become a familiar part of your day, let us know.": "Character 01は、2D1が初めてつくる日用品。いつもの暮らしになじむ、キャンバスのトートバッグです。見慣れたかたちに、長めのストラップ。そして、ふとしたところにのぞく赤。肩にかけたときの収まりから、小さな持ちものの居場所まで、いまも細部を考えています。誰かのためにつくる仕事と同じように、明快なアイデアから始めて、そのものらしさを生むひと工夫を残す。バッグはまだ開発中です。あなたの日常にも迎えたいと思っていただけたら、ぜひお知らせください。",
  "Culturally, people are tired of dating apps. For those who seek love but cannot find the person that’s right for them, there are other services such as matchmaking services and marriage agencies. I personally enjoy watching dating reality TV shows. They might not be 100% authentic, but they do show how people approach dating and what people value in modern romantic relationships.": "マッチングアプリに疲れた、という声をよく耳にします。恋愛をしたいけれど、自分に合う相手が見つからない人のために、マッチメイキングや結婚相談所といったサービスもあります。僕自身、恋愛リアリティ番組を見るのが好きです。すべてがありのままとは限りませんが、人がどう恋愛に向き合い、今の関係の中で何を大切にしているのかが見えてきます。",
  "After consuming all this content, I noticed these services tend to be offered by woman. The advisor tends to be woman. In the show, Indian Matchmaking, the advisor is a woman. In the film, Materialists, the matchmaker acted by Dakota Johnson is a woman. In Japan, the popular founder of the marriage agency IBJ is a woman.": "こうしたコンテンツを見ていて気づいたのは、相談に乗る役割を女性が担っていることが多い、ということです。『インディアン・マッチメイキング』のアドバイザーも女性。映画『マテリアリスツ』でダコタ・ジョンソンが演じるマッチメーカーも女性です。日本でも、人気の結婚相談サービスIBJの創業者は女性です。",
  "As a heterosexual male who lacks the traditional macho values and has always leaned more towards feminine sensitivities, I found it easier to have conversations with woman rather than men. With this, I felt like I can offer a male perspective that are rooted in my past interactions and experience with people, that my female counterparts might not be able to.": "僕は異性愛者の男性ですが、いわゆる「男らしさ」にはあまりなじめず、どちらかといえば女性的とされる感性に親しんできました。男性よりも女性のほうが、自然に話せると感じることも多くあります。そんなこれまでの出会いや経験から、女性の相談相手とはまた違う、男性としての視点を伝えられるのではないかと思っています。",
  "Disclaimer that I’m no professional. This is completely free, pro-bono work.": "専門家としての相談ではありません。料金はいただかず、個人としてお話を聞きます。",
  "On character, familiarity, and the everyday objects we choose to keep. Notes from a design studio with a shop of its own.": "らしさ、親しみ、そして手元に残しておきたい日用品のこと。ショップを持つデザインスタジオからの、ちょっとした考えごと。",
  "2D1 is an independent design studio with a shop of its own. For companies, we find a clear idea and give it character, from the first strategy to the products and brands people use every day. For everyone else, we make everyday objects under our own name, each one hoping to become someone’s": "2D1は、自分たちのショップも持つ独立系デザインスタジオです。企業のためには、明快なアイデアを見つけ、その企業らしさをかたちにします。最初の戦略から、人々が毎日使うプロダクトやブランドまで。そして、みなさんに向けては、2D1の名前で日用品をつくります。どれも、いつか誰かの",
  "Most of the things we own are forgettable. They do their job and then disappear into the background of our lives. But a few of them stay. A mug that has moved with us through three apartments. The pen we always reach for first. A bag that has taken the shape of everything we have carried in it. We don’t keep these things because they are rare or expensive. We keep them because they became familiar.": "持ちものの大半は、あまり記憶に残りません。役目を果たすと、暮らしの背景に溶け込んでいきます。でも、その中のいくつかは、ずっとそばに残ります。三度の引っ越しをともにしたマグカップ。つい最初に手が伸びるペン。入れてきたもののかたちが、少しずつなじんだバッグ。珍しいからでも、高価だからでもなく、すっかり身近な存在になったから、手放せないのです。",
  "A familiar object is not the same as a boring one. The things we grow attached to almost always have something particular about them: a proportion that feels right in the hand, a detail that makes us smile, a way of doing their job that is a little better than it needed to be. That particular something is character. It is what makes us notice an object in the first place, and what makes us forgive its imperfections later.": "身近なものは、退屈なものとは違います。愛着を感じるものには、たいてい、そのものだけの何かがあります。手にしっくりくるバランス、思わず笑顔になる細部、必要以上に少しだけ気の利いた使い心地。その「何か」が、らしさです。最初に目を留める理由になり、やがて少しの不完全さも受け入れられる理由になります。",
  "Character alone isn’t enough, though. Plenty of objects are full of personality and still end up in a drawer. What turns character into attachment is time. An object has to be useful often enough, and easy enough to live with, that it becomes part of the routine. Familiarity gives it meaning.": "でも、らしさだけでは十分ではありません。個性豊かでも、引き出しの奥にしまわれてしまうものはたくさんあります。らしさが愛着に変わるには、時間が必要です。繰り返し役に立ち、無理なく使い続けられて、暮らしの習慣の一部になること。親しみが、そこに意味を与えてくれます。",
  "Objects become meaningful because": "ものに意味が生まれるのは、",
  "This is how we work, for clients and for ourselves. We edit until the idea is clear and the object is easy to live with, then we keep the one detail that gives it a reason to be remembered. Reduction without wit is sterile; wit without reduction is noise. We look for the point where the two meet.": "これが、クライアントのためにも、自分たちのためにも大切にしているつくり方です。アイデアが明快になり、日々に無理なくなじむまでそぎ落とす。そして、記憶に残る理由になるひと工夫を残す。遊び心のない引き算は味気なく、引き算のない遊び心は騒がしい。私たちは、その二つがちょうど出会うところを探しています。",
  "It is also why we care about ordinary things. A water bottle, a tote bag, a tray by the door: these are the objects that spend the most time with us, so they are the ones most worth getting right.": "だからこそ、ありふれたものを大切に考えます。水筒、トートバッグ、玄関のトレイ。いちばん長い時間をともにするものだからこそ、きちんとつくる価値があります。",
  "We think of everything we make as living in the same place, a house full of familiar characters. Some we design for other companies. Some we make under our own name. Some we simply admire and keep around. What connects them is not a style, a price, or a category, but a way of seeing: the belief that the best everyday objects go from having character to becoming a character in someone’s life.": "私たちがつくるものは、みんな同じ場所に暮らしている。親しみのある顔ぶれが集まる、一軒の家のように考えています。ほかの企業のためにデザインするもの。2D1の名前でつくるもの。ただ好きで、手元に置いているもの。それらをつなぐのは、スタイルでも、価格でも、カテゴリーでもありません。日用品は、らしさを持つものから、誰かの暮らしの登場人物になっていく。そんな、ものの見方です。",
  "That is what we are trying to make. Not things that demand attention, but things that earn a place. Things that, after a while, you would miss.": "私たちがつくりたいのは、そういうものです。注目を求めるのではなく、少しずつ居場所を得ていくもの。いつの間にか、なくなると寂しいと感じるもの。",
  "An independent design studio working with founders and small teams on branding and digital products. A place for familiar things with character.": "創業者や少人数のチームとともに、ブランディングとデジタルプロダクトに取り組む独立系デザインスタジオ。身近なものに、らしさを。",
  "Page sections": "ページ内ナビゲーション",
  "2D1 on Instagram (opens in a new tab)": "2D1のInstagram（新しいタブで開きます）",
  "2D1 on Threads (opens in a new tab)": "2D1のThreads（新しいタブで開きます）",
  "2D1 on X (opens in a new tab)": "2D1のX（新しいタブで開きます）",
  "New Fiction on LinkedIn (opens in a new tab)": "New FictionのLinkedIn（新しいタブで開きます）",
  "A Design House": "デザインハウス",
  "2D1 is an independent design house working across brands, digital products, and ideas. We help shape things from early thinking through to how they look, work, and live in the world. Alongside client work, we make things of our own and collaborate with people we like. We call them Familiar Characters — objects and ideas with enough character to earn a place in everyday life.": "2D1は、ブランド、デジタルプロダクト、アイデアを横断して活動する、独立したデザインハウスです。初期の構想から、見た目や使い心地、世の中でのあり方まで、一緒にかたちにしていきます。クライアントワークと並行して、自分たちのものをつくり、気の合う人たちと協働することも。私たちはそれらを「Familiar Characters」と呼んでいます。日々の暮らしの中に居場所を見つける、らしさを持ったものやアイデアです。",
  "We work by editing until the idea is clear, then keeping the one detail that makes you smile. We work with founders, small teams, and independent businesses to make their ideas clear and give them a character of their own. Sometimes that means building a brand from the beginning. Sometimes it means rethinking a website, refining a product, or finding a better way to tell an existing story. From strategy and visual identity to the details of a digital experience, we bring a fresh pair of eyes and a hands-on approach. The aim is work that feels like you, makes sense to the people who use it, and is easy to live with.": "アイデアが明快になるまでそぎ落とし、最後に、思わず笑顔になるひと工夫を残します。創業者や少人数のチーム、小さな事業とともに、アイデアを明快にし、その人たちらしいかたちにしていきます。ブランドをゼロからつくることもあれば、ウェブサイトを見直したり、プロダクトを磨いたり、今ある物語の伝え方を考え直したりすることも。戦略やビジュアルアイデンティティから、デジタル体験の細部まで。新しい視点で向き合い、手を動かしながら、一緒につくります。目指すのは、あなたらしく、使う人にきちんと伝わり、日々に自然となじむデザインです。",
  "2D1 is an independent design house working across brands, digital products, and ideas. We help shape things from early thinking through to how they look, work, and live in the world.": "2D1は、ブランド、デジタルプロダクト、アイデアを横断して活動する、独立したデザインハウスです。初期の構想から、見た目や使い心地、世の中でのあり方まで、一緒にかたちにしていきます。",
  "Alongside client work, we make things of our own and collaborate with people we like. We call them Familiar Characters — objects and ideas with enough character to earn a place in everyday life.": "クライアントワークと並行して、自分たちのものをつくり、気の合う人たちと協働することも。私たちはそれらを「Familiar Characters」と呼んでいます。日々の暮らしの中に居場所を見つける、らしさを持ったものやアイデアです。",
  "Product details": "製品仕様",
  "Material": "素材",
  "Tightly woven black canvas.": "高密度に織られた黒いキャンバス。",
  "Dimensions": "サイズ",
  "Approx. W 38 × H 38 × D 10 cm, excluding the strap.": "約 幅38 × 高さ38 × マチ10cm（ストラップを除く）。",
  "Strap": "ストラップ",
  "One long strap, black outside and red inside. For shoulder or crossbody carry.": "表は黒、裏は赤の長いストラップ。肩掛けにも斜め掛けにも。",
  "Red tag": "赤いタグ",
  "A square woven label, folded into the side seam.": "サイドの縫い目に挟み込んだ、四角い織りネーム。",
  "Interior": "内側",
  "A bottle-holding band and a square pocket for keys, earbuds, and other small things.": "ボトルを支えるバンドと、鍵やイヤホンなどの小物を入れる四角いポケット。",
  "Opening": "開口部",
  "Open top, with a folded and stitched hem.": "折り返して縫製した、留め具のない開口部。",
  "Details": "ディテール",
  "Subtle charcoal pixel eyes on the front; a small embroidered 2D1 logo at the top-center of the back.": "前面には控えめなチャコールグレーのピクセルアイ。背面の上部中央には、小さな2D1の刺繍ロゴ。",
  "Prototype specifications. Dimensions and details may change before production.": "試作段階の仕様です。サイズやディテールは製品化までに変更になる場合があります。",
  "Alongside client work, we make things of our own and collaborate with people we like. We call them": "クライアントワークと並行して、自分たちのものをつくり、気の合う人たちと協働することも。私たちはそれらを「",
  "— objects and ideas with enough character to earn a place in everyday life.": "」と呼んでいます。日々の暮らしの中に居場所を見つける、らしさを持ったものやアイデアです。",
  "The red 2D1 logo on a soft beige background.": "柔らかなベージュの背景に赤い2D1のロゴ。",
  "We work by editing until the idea is clear, then keeping the one detail that makes you smile. We work with founders, small teams, and independent businesses to make their ideas clear and give them a character of their own.": "アイデアが明確になるまで削ぎ落とし、最後に、思わず笑顔になるディテールをひとつ残す。それが私たちの仕事の進め方です。創業者や小さなチーム、独立した事業者とともに、アイデアを整理し、その人たちらしい個性を形にします。",
  "Sometimes that means building a brand from the beginning. Sometimes it means rethinking a website, refining a product, or finding a better way to tell an existing story. From strategy and visual identity to the details of a digital experience, we bring a fresh pair of eyes and a hands-on approach. The aim is work that feels like you, makes sense to the people who use it, and is easy to live with.": "ブランドを一からつくることもあれば、ウェブサイトを見直し、プロダクトを磨き、すでにある物語の伝え方を考え直すこともあります。戦略やビジュアルアイデンティティから、デジタル体験の細部まで。新鮮な視点と手を動かす姿勢で向き合います。目指すのは、あなたらしさがあり、使う人に伝わり、日々に自然となじむものです。",
  "Clear ideas, clear characters.": "アイデアを明確に、個性を鮮明に。",
  "Familiar characters in our everyday lives.": "日々の暮らしに、なじみのある存在を。",
  "Stay in the loop. Follow our process.": "新しい動きと、つくる過程を。",
  "Strategy, Visual Identity, Graphic Design": "戦略、ビジュアルアイデンティティ、グラフィックデザイン",
  "The tote bag is our first everyday object: a canvas tote made to find a place in your routine. A familiar shape, a long strap, and a flash of red where you might not expect it. We’re working through the details, from how it sits on your shoulder to where the small things go inside.": "最初につくる日用品は、毎日の暮らしに居場所を見つけるためのキャンバストートです。なじみのある形、長いストラップ、意外なところにのぞく赤。肩にかけたときの収まりから、小物の居場所まで、細部をひとつずつ考えています。",
  "Like the work we do for others, it starts with a clear idea and keeps the detail that makes it its own. The bag is still in development. If you’d like to see it become a familiar part of your day, let us know.": "誰かのためにつくる仕事と同じように、明確なアイデアから始め、そのものらしさを生むディテールを残します。バッグはまだ開発中です。いつか日々の相棒にしたいと思っていただけたら、ぜひお知らせください。",
  "Approx. W 40 × H 36 × D 10 cm, excluding the strap.": "約 幅40 × 高さ36 × マチ10cm。ストラップを除きます。",
  "One long strap, black outside and red inside. For shoulder carry.": "外側は黒、内側は赤の長いストラップ。肩掛けに対応。",
  "Pockets": "ポケット",
  "A bottle-holding band and a square pocket for small items.": "ボトル用のバンドと、小物用の四角いポケット。",
  "Magnetic clip folded and stitched inside.": "生地の内側に縫い込んだマグネット留め。",
  "Clear ideas, with characters.": "明確なアイデアに、個性を。",
  "Our primary function is a design studio. We work with small teams and businesses to make their ideas clear and give them character. We edit down to its essence, while keeping the one detail that makes you smile.": "私たちの中心にあるのは、デザインスタジオとしての仕事です。小さなチームや事業者とともに、アイデアを明確にし、その個性を形にします。本質まで削ぎ落としながら、思わず笑顔になるディテールをひとつ残します。",
  "Sometimes that means building a brand from the beginning. Sometimes it means rethinking a website, refining a product, or finding a better way to tell an existing story. From strategy to visual identity, and down the pixels of an interface, we bring a fresh pair of eyes and a hands-on approach.": "ブランドを一からつくることもあれば、ウェブサイトを見直し、プロダクトを磨き、すでにある物語の伝え方を考え直すこともあります。戦略からビジュアルアイデンティティ、インターフェースのピクセルひとつまで。新鮮な視点と手を動かす姿勢で向き合います。",
  "Art Direction, Graphic Design, Visual Identity": "アートディレクション、グラフィックデザイン、ビジュアルアイデンティティ",
  "The aim is to create something that is clear, easy, and uniquely you.": "目指すのは、明確で、わかりやすく、あなただけの個性があるものをつくることです。",
  "Our joy for making is at the heart of what we do. Like the work we do for others, it starts with a clear idea and keeps the detail that makes it its own.": "つくる喜びは、私たちの活動の中心にあります。誰かのためにつくる仕事と同じように、明確なアイデアから始め、そのものらしさを生むディテールを残します。",
  "The tote bag is our first everyday item: a canvas tote made to tag along wherever you go. An elementary shape, handy inner pockets, and a flash of red so you know it’s yours. We’re working through the details, from how it feels on your hand to where the small things go inside.": "最初につくる日用品は、どこへ行くにも一緒についてくるキャンバストートです。シンプルな形、便利な内ポケット、自分のものだとわかる赤のアクセント。手に持ったときの感触から、小物の居場所まで、細部をひとつずつ考えています。",
  "The bag is still in development. If you’d like for it to join your days, sign up for updates.": "バッグはまだ開発中です。あなたの日々に迎えたいと思っていただけたら、ぜひお知らせを受け取るためにご登録ください。",
  "Websites, UX/UI, Design Systems": "ウェブサイト、UX/UI、デザインシステム",
  "Character 01 is our first everyday object: a canvas tote made to find a place in your routine. A familiar shape, a long strap, and a flash of red where you might not expect it. We’re working through the details, from how it sits on your shoulder to where the small things go inside. The things we make for ourselves start the same way as our client work: with a clear idea and a detail that makes them their own. The bag is still in development. If you’d like to see it become a familiar part of your day, let us know.": "Character 01は、2D1が初めてつくる日用品。いつもの暮らしになじむ、キャンバスのトートバッグです。見慣れたかたちに、長めのストラップ。そして、ふとしたところにのぞく赤。肩にかけたときの収まりから、小さな持ちものの居場所まで、いまも細部を考えています。誰かのためにつくる仕事と同じように、明快なアイデアから始めて、そのものらしさを生むひと工夫を残す。バッグはまだ開発中です。あなたの日常にも迎えたいと思っていただけたら、ぜひお知らせください。",
  "Subtle charcoal pixel eyes on the front; a small embroidered 2D1 logo centered near the top of the back.": "前面には控えめなチャコール色のピクセルの目。背面の上部中央には、小さな2D1の刺繍ロゴ。",
  "The things we make for ourselves start the same way as our client work: with a clear idea and a detail that makes them their own. The bag is still in development. If you’d like to see it become a familiar part of your day, let us know.": "誰かのためにつくる仕事と同じように、明確なアイデアから始め、そのものらしさを生むディテールを残します。バッグはまだ開発中です。いつか日々の相棒にしたいと思っていただけたら、ぜひお知らせください。",
  "Magnetic closure sewn into the top hem.": "開口部の折り返しに縫い込んだマグネット留め。",
  "At our core, we’re a design studio. We work with small teams and businesses to make their ideas clear and give them character. We strip each idea down to its essence, keeping the one detail that makes you smile.": "私たちの中心にあるのは、デザインスタジオとしての仕事です。小さなチームや事業者とともに、アイデアを明確にし、その個性を形にします。それぞれのアイデアを本質まで削ぎ落としながら、思わず笑顔になるディテールをひとつ残します。",
  "Sometimes that means building a brand from the beginning. Sometimes it means rethinking a website, refining a product, or finding a better way to tell an existing story. From strategy and visual identity down to the pixels of an interface, we bring a fresh pair of eyes and a hands-on approach.": "ブランドを一からつくることもあれば、ウェブサイトを見直し、プロダクトを磨き、すでにある物語の伝え方を考え直すこともあります。戦略からビジュアルアイデンティティ、インターフェースのピクセルひとつまで。新鮮な視点と手を動かす姿勢で向き合います。",
  "The aim is to create something that is clear, intuitive, and uniquely you.": "目指すのは、明確で、直感的に使えて、あなただけの個性があるものをつくることです。",
  "The joy of making is at the heart of what we do. The things we make for ourselves start the same way as our client work: with a clear idea and a detail that makes them their own.": "つくる喜びは、私たちの活動の中心にあります。自分たちのためにつくるものも、クライアントのための仕事と同じところから始まります。明確なアイデアと、そのものらしさを生むディテールから。",
  "The tote bag is our first everyday item: a canvas tote made to tag along wherever you go. A simple shape, handy inner pockets, and a flash of red so you know it’s yours. We’re working through the details, from how the strap feels in your hand to where the small things go inside.": "最初につくる日用品は、どこへ行くにも一緒についてくるキャンバストートです。シンプルな形、便利な内ポケット、自分のものだとわかる赤のアクセント。ストラップを手に持ったときの感触から、小物の居場所まで、細部をひとつずつ考えています。",
  "The bag is still in development. If you’d like it to become part of your day, sign up for updates.": "バッグはまだ開発中です。あなたの日々に迎えたいと思っていただけたら、ぜひお知らせを受け取るためにご登録ください。",
  "Alongside client work, we make things of our own and collaborate with people we like. We call these objects and ideas": "クライアントワークと並行して、自分たちのものをつくり、気の合う人たちと協働しています。私たちは、こうしたオブジェクトやアイデアを",
  "— things with enough character to earn a place in everyday life.": "と呼びます。日々の暮らしに居場所を見つけるだけの個性を持ったものたちです。"
};
