#!/usr/bin/env python3
"""Build Familiar Characters: static pages, images, and share cards.

Content lives in _familiar-characters/ (not published): one text file per
Character in characters/, original images in images/, and the index settings
in collection.md. This script turns it into:

  familiar-characters/index.html               the index: the grid, the House, and
                                               the overlay each Character opens in
  familiar-characters/NNN-slug/index.html      each Character on its own: the same
                                               overlay, as a page (shareable, indexable)
  img/characters/*.webp                        resized images, 480 to 1800 px wide,
                                               and red-tinted ones for the House
  img/characters/share/*.jpg                   1200 × 630 share images
  sitemap.xml                                  published Characters only

    python3 scripts/build_characters.py           build
    python3 scripts/build_characters.py --check   check the content, write nothing

Needs Python 3.9+ and Pillow (python3 -m pip install Pillow). The pages link to
the site's own css/ and js/, and take the footer from index.html, so the two
stay the same.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from urllib.parse import urlparse

try:
    from PIL import Image, ImageDraw, ImageFont, ImageOps
except ImportError:
    sys.exit('This build needs Pillow: python3 -m pip install Pillow')

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / '_familiar-characters'
OUT = ROOT / 'familiar-characters'
IMG = ROOT / 'img' / 'characters'
SHARE = IMG / 'share'
CACHE = SRC / '.build-cache.json'
SITE = 'https://2d1.studio'
INDEX_URL = f'{SITE}/familiar-characters/'
MARK = '<!-- Generated by scripts/build_characters.py from _familiar-characters/. Edit those files and rebuild; changes made here are overwritten. -->'

WIDTHS = (480, 800, 1200, 1800)   # image variants; cards never ask for 1800
CELL = 4 / 5                       # card image box, width / height (--cell in css/characters.css)
IMAGE_VERSION = '1'                # bump to re-encode every image
TINT_WIDTHS = (320, 640)           # the House's red-tinted squares
TINT_VERSION = '1'                 # bump to re-tint every image
TINT_GAMMA, TINT_CUTOFF = 1.1, 2   # the duotone curve: ink shadows, Icon Red highlights
SHARE_VERSION = '2'                # bump to redraw every share image
FILE_RE = re.compile(r'^(\d{3,})-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$')
KINDS = {'found': '', 'made-with': 'Made with 2D1', 'made-by-2d1': 'Made by 2D1'}
FIELDS = {'number', 'title', 'maker', 'designer', 'designer-label', 'year', 'category', 'country', 'material',
          'dimensions', 'kind', 'tags', 'source', 'added', 'placeholder', 'summary'}
MONTHS = 'January February March April May June July August September October November December'.split()

# Card widths per breakpoint, from .fc-grid in css/characters.css.
GRID = ((1800, '20vw - 32px'), (1100, '25vw - 32px'), (900, '33.3vw - 32px'), (700, '33.3vw - 24px'), (0, '50vw - 18px'))

FONT = ROOT / 'fonts' / 'Rand' / 'Rand-Regular.ttf'
MONO = ROOT / 'fonts' / 'Rand Mono' / 'RandMono-Regular.ttf'
RED, INK, INK_SOFT, WHITE = (255, 43, 0), (22, 22, 26), (91, 91, 97), (255, 255, 255)
LOGO_PATHS = (  # the 2D1 logo, from index.html (viewBox 0 0 775 280)
    'M1.72214 0L208.038 0C249.301 0 280.74 29.4737 280.74 69.7544C280.74 106.105 254.213 132.632 215.898 139.509H280.982V280H0V211.228C0 181.754 18.6667 153.263 55.0175 139.509L1.72214 139.509V0Z',
    'M774.705 0V280H632.911V139.51H562V0H774.705Z',
    'M411.749 0C498.083 0 554.082 55.9998 554.082 140C554.082 223.999 498.083 280 411.749 280H288.625V0H411.749Z',
)


class BuildError(Exception):
    pass


@dataclass
class Picture:
    file: str
    alt: str
    credit: str
    width: int = 0
    height: int = 0
    color: str | None = None      # average colour, shown while the image loads
    digest: str = ''
    variants: list = field(default_factory=list)   # [(width, file name)]
    tints: list = field(default_factory=list)      # the same, tinted red for the House

    @property
    def ratio(self) -> float:
        return self.width / self.height


@dataclass
class Character:
    number: str
    slug: str                      # "012-clear-water-bottle": file, folder, and URL
    path: Path
    title: str
    maker: str
    designer: str
    designer_label: str
    year: str
    category: str
    country: str
    material: str
    dimensions: str
    kind: str
    tags: list
    source: str
    added: date | None
    placeholder: bool
    summary: str
    note: list                     # paragraphs, as written
    picture: Picture
    share: str = ''

    @property
    def url(self) -> str:
        return f'{INDEX_URL}{self.slug}/'


# Text -------------------------------------------------------------------------

def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def esc(text: str) -> str:
    return html.escape(text, quote=True)


def smart(text: str) -> str:
    """Typographer's quotes and apostrophes, as in the rest of the site."""
    text = re.sub(r"(?<=\w)'(?=\w)", '’', text)
    text = re.sub(r"'(?=\d\ds\b)", '’', text)
    text = re.sub(r"(^|[\s(\[—–-])'", r'\1‘', text)
    text = text.replace("'", '’')
    text = re.sub(r'(^|[\s(\[‘—–-])"', r'\1“', text)
    return text.replace('"', '”')


LINK_RE = re.compile(r'\[([^\]]+)\]\((https?://[^\s)]+|/[^\s)]*)\)')


def inline(text: str, root: str) -> str:
    """One paragraph of a note: escaped, with [text](url) links."""
    out, last = [], 0
    for m in LINK_RE.finditer(text):
        out.append(esc(smart(text[last:m.start()])))
        url, label = m.group(2), esc(smart(m.group(1)))
        if url.startswith('/'):
            out.append(f'<a href="{esc(root + url[1:])}">{label}</a>')
        else:
            out.append(f'<a href="{esc(url)}" target="_blank" rel="noopener noreferrer">{label}<span class="sr-only"> (opens in a new tab)</span></a>')
        last = m.end()
    out.append(esc(smart(text[last:])))
    return ''.join(out)


def plain(text: str) -> str:
    return smart(LINK_RE.sub(r'\1', text))


def first_sentence(text: str) -> str:
    m = re.match(r'(.+?[.!?])(?:\s|$)', text)
    return m.group(1) if m else text


def clip(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[:limit - 1].rsplit(' ', 1)[0].rstrip(',;:') + '…'


def split_list(value: str) -> list:
    return [v.strip() for v in value.split(',') if v.strip()]


def paragraphs(body: str) -> list:
    blocks = re.split(r'\n[ \t]*\n', body.strip())
    return [' '.join(line.strip() for line in b.split('\n')) for b in blocks if b.strip()]


def month(d: date) -> str:
    return f'{MONTHS[d.month - 1]} {d.year}'


def credit(c: Character) -> str:
    """“Designer for Maker, 2022”, or as much of it as is known."""
    if c.designer and c.maker:
        who = f'{c.designer} for {c.maker}' if c.designer_label == 'Designed by' else f'{c.designer}, {c.maker}'
    else:
        who = c.designer or c.maker
    return ', '.join(x for x in (who, c.year) if x)


def token(text: str) -> str:
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')


# Reading content ----------------------------------------------------------------

def read(path: Path):
    """Settings between two lines of ---, then the text."""
    text = path.read_text(encoding='utf-8').replace('\r\n', '\n')
    m = re.match(r'---[ \t]*\n(.*?)\n---[ \t]*(?:\n|$)(.*)', text, re.S)
    if not m:
        raise BuildError(f'{rel(path)}: must begin with its settings between two lines of ---')
    meta, images = {}, []
    for n, line in enumerate(m.group(1).split('\n'), 2):
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        key, sep, value = s.partition(':')
        key = key.strip().lower()
        if not sep or not re.fullmatch(r'[a-z][a-z0-9-]*', key):
            raise BuildError(f'{rel(path)}, line {n}: expected “key: value”, found “{s}”')
        if key == 'image':
            images.append((value.strip(), n))
        elif key in meta:
            raise BuildError(f'{rel(path)}, line {n}: “{key}” is set twice')
        else:
            meta[key] = value.strip()
    return meta, images, m.group(2)


def load_settings(errors: list) -> dict:
    path = SRC / 'collection.md'
    try:
        meta, _, body = read(path)
    except (BuildError, OSError) as e:
        errors.append(str(e))
        return {}
    s = {
        'title': meta.get('title') or 'Familiar Characters',
        'description': meta.get('description', ''),
        'order': meta.get('order', 'newest'),
        'filters': meta.get('filters', 'off'),
        'essay_url': meta.get('essay-url', ''),
        'essay_link': meta.get('essay-link') or 'About Familiar Characters',
        'essay_kicker': meta.get('essay-kicker') or 'From the House',
        'essay_title': meta.get('essay-title', ''),
        'end_note': meta.get('end-note', ''),
        'categories': split_list(meta.get('categories', '')),
        'tags': [t.lower() for t in split_list(meta.get('tags', ''))],
        'intro': paragraphs(body),
    }
    if s['order'] not in ('newest', 'oldest'):
        errors.append(f'{rel(path)}: order is “newest” or “oldest”')
    if s['filters'] not in ('off', 'category'):
        errors.append(f'{rel(path)}: filters is “off” or “category”')
    if not s['categories']:
        errors.append(f'{rel(path)}: list the categories, e.g. “categories: Home, Kitchen, Desk”')
    if s['essay_url'] and not re.match(r'(https?://|/)', s['essay_url']):
        errors.append(f'{rel(path)}: essay-url is a full address (https://…) or a path on this site (/…)')
    return s


def load_characters(settings: dict, errors: list, warnings: list) -> list:
    chars, numbers = [], {}
    categories = {c.lower(): c for c in settings.get('categories', [])}
    for path in sorted((SRC / 'characters').glob('*.md')):
        if path.name.startswith('_'):
            continue
        where = rel(path)
        m = FILE_RE.match(path.name)
        if not m:
            errors.append(f'{where}: name the file with its number and a short name, like 013-folding-chair.md')
            continue
        number = m.group(1)
        if int(number) in numbers:
            errors.append(f'{where}: No. {number} is already used by {numbers[int(number)]}')
            continue
        numbers[int(number)] = rel(path)
        try:
            meta, images, body = read(path)
        except (BuildError, OSError) as e:
            errors.append(str(e))
            continue
        problems = []
        for key in meta.keys() - FIELDS:
            problems.append(f'unknown setting “{key}” (a typo?)')
        if meta.get('number') and meta['number'] != number:
            problems.append(f'number {meta["number"]} does not match the file name ({number})')
        title = meta.get('title', '')
        if not title:
            problems.append('needs a title')
        category = categories.get(meta.get('category', '').lower())
        if not category:
            problems.append(f'category is one of: {", ".join(settings.get("categories", []))} (add new ones in collection.md)')
        kind = meta.get('kind', 'found').lower()
        if kind not in KINDS:
            problems.append('kind is found, made-with, or made-by-2d1')
        tags = [t.lower() for t in split_list(meta.get('tags', ''))]
        unknown = [t for t in tags if settings.get('tags') and t not in settings['tags']]
        if unknown:
            warnings.append(f'{where}: tag{"s" if len(unknown) > 1 else ""} not in collection.md: {", ".join(unknown)}')
        source = meta.get('source', '')
        if source and not re.match(r'https?://', source):
            problems.append('source is a full address, starting with https://')
        added = None
        if meta.get('added'):
            try:
                added = date.fromisoformat(meta['added'])
            except ValueError:
                problems.append('added is a date like 2026-09-29')
        placeholder = meta.get('placeholder', 'no').lower()
        if placeholder not in ('yes', 'no', 'true', 'false'):
            problems.append('placeholder is yes or no')
        note = paragraphs(body)
        if not note:
            problems.append('needs a note (the text under the second ---)')
        picture = None
        if not images:
            problems.append('needs an image')
        else:
            value, line = images[0]
            parts = [p.strip() for p in value.split('|')]
            if len(parts) < 2 or not parts[0] or not parts[1]:
                problems.append(f'line {line}: image is “file | alt text | credit” (alt text is required)')
            elif not (SRC / 'images' / parts[0]).is_file():
                problems.append(f'line {line}: no file _familiar-characters/images/{parts[0]}')
            else:
                picture = Picture(parts[0], parts[1], parts[2] if len(parts) > 2 else '')
            if len(images) > 1:
                warnings.append(f'{where}: one image per Character; using the first ({parts[0]})')
        if problems:
            errors.extend(f'{where}: {p}' for p in problems)
            continue
        chars.append(Character(
            number=number, slug=path.stem, path=path, title=smart(title),
            maker=smart(meta.get('maker', '')), designer=smart(meta.get('designer', '')),
            designer_label=meta.get('designer-label') or 'Designed by', year=meta.get('year', ''),
            category=category, country=smart(meta.get('country', '')), material=smart(meta.get('material', '')),
            dimensions=smart(meta.get('dimensions', '')), kind=kind, tags=tags, source=source, added=added,
            placeholder=placeholder in ('yes', 'true'),
            summary=smart(meta['summary']) if meta.get('summary') else first_sentence(plain(note[0])),
            note=note, picture=picture,
        ))
    return chars


# Images ---------------------------------------------------------------------------

def variant_widths(width: int) -> list:
    return sorted({w for w in WIDTHS if w < width} | {min(width, WIDTHS[-1])})


def tint(im: Image.Image) -> Image.Image:
    """The House's duotone: shadows go to ink, light goes to Icon Red, one red only."""
    lut = []
    for channel in range(3):
        for i in range(256):
            t = (i / 255) ** TINT_GAMMA
            lut.append(round(INK[channel] + (RED[channel] - INK[channel]) * t))
    gray = ImageOps.autocontrast(ImageOps.grayscale(im.convert('RGB')), cutoff=TINT_CUTOFF)
    out = gray.convert('RGB').point(lut)
    if im.mode == 'RGBA':
        out.putalpha(im.getchannel('A'))
    return out


def prepare(pic: Picture, c: Character, cache: dict, produced: set) -> None:
    """Resize the original into WebP variants and tinted ones, once; remember its size and colour."""
    path = SRC / 'images' / pic.file
    data = path.read_bytes()
    pic.digest = hashlib.sha1(data + IMAGE_VERSION.encode()).hexdigest()[:10]
    tint_digest = hashlib.sha1(data + (IMAGE_VERSION + TINT_VERSION).encode()).hexdigest()[:10]

    def names():
        pic.variants = [(w, f'{c.slug}-{w}.{pic.digest}.webp') for w in variant_widths(pic.width)]
        pic.tints = [(w, f'{c.slug}-tint-{w}.{tint_digest}.webp') for w in sorted({min(w, pic.width) for w in TINT_WIDTHS})]

    known = cache.get(pic.digest)
    if known:
        pic.width, pic.height, pic.color = known['w'], known['h'], known.get('color')
        names()
        if all((IMG / name).exists() for _, name in pic.variants + pic.tints):
            produced.update(name for _, name in pic.variants + pic.tints)
            return
    with Image.open(path) as original:
        icc = original.info.get('icc_profile')
        im = ImageOps.exif_transpose(original)
        alpha = im.mode in ('RGBA', 'LA', 'PA') or 'transparency' in im.info
        im = im.convert('RGBA' if alpha else 'RGB')
    pic.width, pic.height = im.size
    pic.color = None if alpha else '#%02x%02x%02x' % im.resize((1, 1), Image.Resampling.BOX).getpixel((0, 0))[:3]
    cache[pic.digest] = {'w': pic.width, 'h': pic.height, 'color': pic.color}
    names()
    red = None
    for (w, name), tinted in [(v, False) for v in pic.variants] + [(v, True) for v in pic.tints]:
        produced.add(name)
        out = IMG / name
        if out.exists():
            continue
        source = im
        if tinted:
            red = red or tint(im)
            source = red
        frame = source if w == pic.width else source.resize((w, max(1, round(pic.height * w / pic.width))), Image.Resampling.LANCZOS)
        options = {'quality': 80, 'method': 6}   # no EXIF is copied: phone photos keep their location to themselves
        if icc and not tinted:
            options['icc_profile'] = icc
        if alpha:
            options['alpha_quality'] = 90
        frame.save(out, 'WEBP', **options)


def srcset(pic: Picture, root: str, limit: int = WIDTHS[-1], tinted: bool = False) -> str:
    return ', '.join(f'{root}img/characters/{name} {w}w' for w, name in (pic.tints if tinted else pic.variants) if w <= limit)


def fallback(pic: Picture, root: str, limit: int) -> str:
    fits = [name for w, name in pic.variants if w <= limit]
    return f'{root}img/characters/{fits[-1]}'


def card_sizes(pic: Picture) -> str:
    # Narrow images don't fill their box, so ask for less.
    factor = min(1.0, pic.ratio / CELL)
    parts = []
    for min_width, width in GRID:
        size = f'calc({width})' if factor > .97 else f'calc(({width}) * {factor:.2f})'
        parts.append(f'(min-width: {min_width}px) {size}' if min_width else size)
    return ', '.join(parts)


def picture_style(pic: Picture) -> str:
    return f'--r:{pic.ratio:.4f}' + (f';background-color:{pic.color}' if pic.color else '')


# Share images ----------------------------------------------------------------------

def svg_polygons(d: str, steps: int = 24) -> list:
    tokens = re.findall(r'[MLHVCZ]|-?(?:\d+\.?\d*|\.\d+)', d)
    polys, points, i, cmd, x, y = [], [], 0, '', 0.0, 0.0

    def num() -> float:
        nonlocal i
        i += 1
        return float(tokens[i - 1])

    while i < len(tokens):
        if tokens[i].isalpha():
            cmd = tokens[i]
            i += 1
        if cmd == 'M':
            x, y = num(), num()
            points, cmd = [(x, y)], 'L'
        elif cmd == 'L':
            x, y = num(), num()
            points.append((x, y))
        elif cmd == 'H':
            x = num()
            points.append((x, y))
        elif cmd == 'V':
            y = num()
            points.append((x, y))
        elif cmd == 'C':
            x1, y1, x2, y2, x3, y3 = [num() for _ in range(6)]
            for s in range(1, steps + 1):
                t = s / steps
                u = 1 - t
                points.append((u ** 3 * x + 3 * u * u * t * x1 + 3 * u * t * t * x2 + t ** 3 * x3,
                               u ** 3 * y + 3 * u * u * t * y1 + 3 * u * t * t * y2 + t ** 3 * y3))
            x, y = x3, y3
        elif cmd == 'Z':
            polys.append(points)
            points = []
    return polys


LOGO = [p for d in LOGO_PATHS for p in svg_polygons(d)]


def logo(width: int, color: tuple) -> Image.Image:
    height = round(width * 280 / 775)
    scale = width * 4 / 775
    mask = Image.new('L', (width * 4, height * 4), 0)
    draw = ImageDraw.Draw(mask)
    for poly in LOGO:
        draw.polygon([(px * scale, py * scale) for px, py in poly], fill=255)
    out = Image.new('RGBA', (width, height), color + (0,))
    out.putalpha(mask.resize((width, height), Image.Resampling.LANCZOS))
    return out


def text_width(text: str, font, tracking: float = 0) -> float:
    return font.getlength(text) + tracking * max(len(text) - 1, 0)


def draw_text(draw, x: float, y: float, text: str, font, fill, tracking: float = 0) -> float:
    """Draw text with its baseline at y; tracking is extra space between letters, in px."""
    if not tracking:
        draw.text((x, y), text, font=font, fill=fill, anchor='ls')
    else:
        for i, ch in enumerate(text):
            draw.text((x + font.getlength(text[:i]) + tracking * i, y), ch, font=font, fill=fill, anchor='ls')
    return x + text_width(text, font, tracking)


def wrap(text: str, font, width: float, tracking: float = 0) -> list:
    lines, line = [], ''
    for word in text.split():
        test = f'{line} {word}'.strip()
        if line and text_width(test, font, tracking) > width:
            lines.append(line)
            line = word
        else:
            line = test
    return lines + [line] if line else lines


def shelve(canvas: Image.Image, pic: Picture, box: tuple, right: bool = False) -> None:
    """Fit a picture into box without cropping, standing on its bottom-left (or bottom-right) corner."""
    x0, y0, x1, y1 = box
    with Image.open(SRC / 'images' / pic.file) as original:
        im = ImageOps.exif_transpose(original).convert('RGBA')
    scale = min((x1 - x0) / im.width, (y1 - y0) / im.height)
    im = im.resize((max(1, round(im.width * scale)), max(1, round(im.height * scale))), Image.Resampling.LANCZOS)
    canvas.paste(im, (x1 - im.width if right else x0, y1 - im.height), im)


def share_base(fonts: dict) -> Image.Image:
    """White card with the site's red bar: the active nav item on the left, the logo in the middle."""
    card = Image.new('RGB', (1200, 630), WHITE)
    draw = ImageDraw.Draw(card)
    draw.rectangle((0, 0, 1199, 83), fill=RED)
    draw.rectangle((48, 37, 56, 45), fill=WHITE)
    draw_text(draw, 68, 48, 'FAMILIAR CHARACTERS', fonts['mono18'], WHITE, 0.9)
    mark = logo(104, WHITE)
    card.paste(mark, ((1200 - mark.width) // 2, (84 - mark.height) // 2), mark)
    return card


def share_character(c: Character, fonts: dict, produced: set) -> None:
    lines = [c.number, c.title, c.maker, c.designer, c.designer_label, c.category, c.year, c.picture.digest]
    digest = hashlib.sha1('\n'.join([SHARE_VERSION] + lines).encode()).hexdigest()[:10]
    c.share = f'{c.slug}.{digest}.jpg'
    produced.add(c.share)
    if (SHARE / c.share).exists():
        return
    card = share_base(fonts)
    draw = ImageDraw.Draw(card)
    shelve(card, c.picture, (48, 132, 600, 582), right=True)   # against the text
    x, width = 648, 504
    draw_text(draw, x, 150, f'NO. {c.number}', fonts['mono22'], INK_SOFT, 1.1)
    for size in (58, 50, 44, 38):
        font = ImageFont.truetype(str(FONT), size)
        title = wrap(c.title, font, width, -.03 * size)
        if len(title) <= 4:
            break
    y = 150 + 26 + round(size * .8)
    for line in title:
        draw_text(draw, x, y, line, font, INK, -.03 * size)
        y += round(size * 1.04)
    y += 18
    for text, color in ((c.maker, INK), (f'{c.designer_label} {c.designer}' if c.designer else '', INK_SOFT)):
        for line in wrap(text, fonts['sans28'], width, -.3)[:2]:
            draw_text(draw, x, y, line, fonts['sans28'], color, -.3)
            y += 36
    meta = ' / '.join(v for v in (c.category, c.year) if v).upper()
    draw_text(draw, x, 582, meta, fonts['mono20'], INK_SOFT, 1)
    card.save(SHARE / c.share, 'JPEG', quality=86, optimize=True, progressive=True)


def share_collection(chars: list, settings: dict, fonts: dict, produced: set) -> str:
    shelf = [c.picture for c in chars[:5]]
    intro = plain(settings['intro'][0]) if settings['intro'] else ''
    digest = hashlib.sha1('\n'.join([SHARE_VERSION, settings['title'], intro] + [p.digest for p in shelf]).encode()).hexdigest()[:10]
    name = f'familiar-characters.{digest}.jpg'
    produced.add(name)
    if (SHARE / name).exists():
        return name
    card = share_base(fonts)
    draw = ImageDraw.Draw(card)
    title_font = ImageFont.truetype(str(FONT), 84)
    end = draw_text(draw, 44, 206, settings['title'], title_font, INK, -.045 * 84)
    draw_text(draw, end - .045 * 84, 206, '.', title_font, RED)
    y = 252
    for line in wrap(intro, fonts['sans26'], 620, -.2)[:2]:
        draw_text(draw, 48, y, line, fonts['sans26'], INK_SOFT, -.2)
        y += 34
    for i, pic in enumerate(shelf):
        x = 48 + i * (184 + 24)
        shelve(card, pic, (x, 352, x + 184, 582))
    card.save(SHARE / name, 'JPEG', quality=86, optimize=True, progressive=True)
    return name


# Pages --------------------------------------------------------------------------------

def jsonld(data) -> str:
    return json.dumps(data, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')


def head(*, root: str, title: str, description: str, canonical: str, robots: str, og_type: str,
         og_title: str, image: str, image_alt: str, data, bar: bool = True, base: bool = False) -> str:
    # The index changes its address to a Character's while one is open; a base
    # fixed at load keeps its relative links pointing where they did.
    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">{"""
  <base href="./">""" if base else ""}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(description)}">
  <meta name="robots" content="{robots}">
  <meta name="theme-color" content="#FF2B00">
  <link rel="canonical" href="{canonical}">
  <meta property="og:type" content="{og_type}">
  <meta property="og:site_name" content="2D1">
  <meta property="og:title" content="{esc(og_title)}">
  <meta property="og:description" content="{esc(description)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{image}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="{esc(image_alt)}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{esc(og_title)}">
  <meta name="twitter:description" content="{esc(description)}">
  <meta name="twitter:image" content="{image}">
  <link rel="icon" href="{root}img/brand/2d1-icon.svg" type="image/svg+xml">
  <link rel="icon" href="{root}img/brand/2d1-icon.png" type="image/png" sizes="32x32">
  <link rel="apple-touch-icon" href="{root}img/brand/2d1-apple-touch.png" sizes="180x180">
  <link rel="preload" href="{root}fonts/Rand/Rand-Regular.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="preload" href="{root}fonts/Rand Mono/RandMono-Regular.woff2" as="font" type="font/woff2" crossorigin>
  <script>document.documentElement.classList.add('js');</script>
  <link rel="stylesheet" href="{root}css/fonts.css">
  <link rel="stylesheet" href="{root}css/style.css">
  <link rel="stylesheet" href="{root}css/characters.css">{f"""
  <script src="{root}js/bar.js" defer></script>""" if bar else ""}
  <script src="{root}js/characters.js" defer></script>
  <script type="application/ld+json">{jsonld(data)}</script>
</head>'''


def bar(root: str, logo_svg: str) -> str:
    return f'''  <a class="skip-link" href="#main">Skip to content</a>

  <header class="bar">
    <button class="bar-menu" type="button" aria-expanded="false" aria-controls="bar-nav">Menu</button>
    <nav class="bar-nav" id="bar-nav" aria-label="Sections"><a href="{root}#studio">Studio</a><a href="{root}#shop">Shop</a><a href="./" aria-current="page">Familiar Characters</a></nav>
    <a class="bar-logo" href="{root}" aria-label="2D1, home">{logo_svg}</a>
    <a class="btn btn-bar" href="{root}#updates">Get updates</a>
  </header>'''


def card(c: Character, *, eager: bool = False, high: bool = False) -> str:
    """One Character on the index. The House is drawn from these cards too."""
    pic, root = c.picture, '../'
    attrs = [f'data-no="{c.number}"', f'data-slug="{c.slug}"', f'data-category="{token(c.category)}"', f'data-kind="{c.kind}"']
    if c.tags:
        attrs.append(f'data-tags="{esc(" ".join(token(t) for t in c.tags))}"')
    attrs.append(f'data-tint="{esc(srcset(pic, root, tinted=True))}"')
    attrs.append(f'data-ratio="{pic.ratio:.4f}"')
    loading = 'eager' if eager else 'lazy'
    priority = ' fetchpriority="high"' if high else ''
    return f'''      <li class="fc-card" {" ".join(attrs)}>
        <div class="fc-card-media"><img class="fc-img" src="{fallback(pic, root, 800)}" srcset="{srcset(pic, root, 1200)}" sizes="{card_sizes(pic)}" width="{pic.width}" height="{pic.height}" alt="" loading="{loading}" decoding="async"{priority} style="{picture_style(pic)}"></div>
        <p class="fc-card-meta"><span class="fc-no">No. {c.number}</span><span class="fc-cat">{esc(c.category)}</span></p>
        <h3 class="fc-card-title"><a class="fc-card-link" href="{c.slug}/">{esc(c.title)}</a></h3>
        <p class="fc-card-by">{esc(credit(c))}</p>
        <p class="fc-card-note">{esc(c.summary)}</p>
      </li>'''


def site_path(url: str, root: str) -> str:
    return root + url[1:] if url.startswith('/') else url


def index_page(chars: list, settings: dict, share: str, footer: str, logo_svg: str) -> str:
    root = '../'
    count = f'{len(chars)} Character{"" if len(chars) == 1 else "s"}'
    order = 'newest first' if settings['order'] == 'newest' else 'oldest first'
    placeholders = any(c.placeholder for c in chars)
    intro = settings['intro']
    lede = ''
    for i, p in enumerate(intro):
        more = ' class="fc-lede-more"' if i else ''
        lede += f'\n        <p{more}>{inline(p, root)}</p>'
    essay = settings['essay_url']
    if essay:
        lede += f'\n        <p class="fc-essay-link"><a class="fc-arrow-link" href="{esc(site_path(essay, root))}">{esc(settings["essay_link"])} <span aria-hidden="true">→</span></a></p>'
    filters = ''
    if settings['filters'] == 'category' and chars:
        used = [cat for cat in settings['categories'] if any(c.category == cat for c in chars)]
        buttons = [f'<li><button class="fc-filter-btn" type="button" data-filter="" aria-pressed="true">All</button></li>']
        buttons += [f'<li><button class="fc-filter-btn" type="button" data-filter="{token(cat)}" aria-pressed="false">{esc(cat)} <span class="fc-filter-n">{sum(c.category == cat for c in chars)}</span></button></li>' for cat in used]
        filters = f'\n        <nav class="fc-filter" aria-label="Categories" hidden><ul role="list">{"".join(buttons)}</ul></nav>'
    cards = '\n'.join(card(c, eager=i < 5, high=i < 2) for i, c in enumerate(chars))
    end = ''
    if settings['end_note']:
        end += f'\n      <div class="fc-end-note"><p>{esc(smart(settings["end_note"]))}</p><p><a class="fc-arrow-link" href="{root}#updates">Get updates <span aria-hidden="true">→</span></a></p></div>'
    if essay and settings['essay_title']:
        end += f'''
      <aside class="fc-essay" aria-labelledby="fc-essay-title">
        <p class="fc-label">{esc(settings["essay_kicker"])}</p>
        <h2 class="fc-essay-title" id="fc-essay-title"><a href="{esc(site_path(essay, root))}">{esc(smart(settings["essay_title"]))}</a></h2>
        <p class="fc-essay-read" aria-hidden="true">Read essay →</p>
      </aside>'''
    description = settings['description'] or (plain(intro[0]) if intro else settings['title'])
    end_section = f'''

    <section class="fc-end" aria-label="End of the collection">{end}
    </section>''' if end else ''
    data = {
        '@context': 'https://schema.org', '@type': 'CollectionPage', 'name': settings['title'],
        'description': description, 'url': INDEX_URL,
        'isPartOf': {'@type': 'WebSite', 'name': '2D1', 'url': f'{SITE}/'},
        'publisher': {'@type': 'Organization', 'name': '2D1', 'url': f'{SITE}/', 'logo': f'{SITE}/img/brand/logo_red.svg'},
        'mainEntity': {'@type': 'ItemList', 'numberOfItems': len(chars),
                       'itemListOrder': 'https://schema.org/ItemListOrderDescending' if settings['order'] == 'newest' else 'https://schema.org/ItemListOrderAscending',
                       'itemListElement': [{'@type': 'ListItem', 'position': i, 'url': c.url, 'name': c.title} for i, c in enumerate(chars, 1)]},
    }
    top = head(root=root, title=f'{settings["title"]} — 2D1', description=description, canonical=INDEX_URL,
               robots='noindex, follow' if placeholders else 'index, follow', og_type='website',
               og_title=f'{settings["title"]} — 2D1', image=f'{SITE}/img/characters/share/{share}',
               image_alt=f'{settings["title"]}: a shelf of everyday objects collected by 2D1.', data=data, base=True)
    return f'''{top}
<body class="fc-page">
{MARK}
{bar(root, logo_svg)}

  <main id="main" class="fc">
    <header class="fc-intro">
      <h1 class="fc-title">{esc(settings["title"])}<span class="sign-stop" aria-hidden="true">.</span></h1>
      <div class="fc-lede">{lede}
      </div>
    </header>

    <section class="fc-index" aria-labelledby="fc-index-title">
      <div class="fc-head">
        <h2 class="fc-label fc-index-label" id="fc-index-title">Index</h2>
        <div class="fc-views" role="group" aria-label="View" hidden><button class="fc-view-btn" type="button" data-view="index" aria-pressed="true">Index</button><button class="fc-view-btn" type="button" data-view="house" aria-pressed="false">House</button></div>{filters}
        <p class="fc-label fc-count" data-count="{count}" aria-live="polite">{count}, {order}</p>
      </div>
      <ul class="fc-grid" role="list">
{cards}
      </ul>
      <div class="fc-house" hidden></div>
    </section>{end_section}
  </main>

  {footer}

  <!-- Each Character opens here, over the collection (js/characters.js fills it). -->
  <dialog class="fc-dialog" aria-labelledby="fc-sheet-title">
    <div class="fc-sheet"></div>
    <p class="sr-only" id="fc-sheet-status" aria-live="polite"></p>
  </dialog>
</body>
</html>
'''


def sheet_page(c: Character, before: Character | None, after: Character | None, logo_svg: str) -> str:
    """A Character: the overlay the index opens, also standing on its own at the Character's address."""
    root, up = '../../', '../'
    pic = c.picture
    classification = [c.category] + ([c.year] if c.year else []) + ([KINDS[c.kind]] if KINDS[c.kind] else [])
    by = ''
    if c.maker:
        by += f'<span class="fc-entry-maker">{esc(c.maker)}</span>'
    if c.designer:
        by += f'<span class="fc-entry-designer">{esc(c.designer_label)} {esc(c.designer)}</span>'
    note = '\n'.join(f'          <p>{inline(p, root)}</p>' for p in c.note)
    specs = []
    for label, value in (('Material', c.material), ('Dimensions', c.dimensions), ('Country', c.country)):
        if value:
            specs.append((label, esc(value)))
    if c.source:
        host = urlparse(c.source).netloc.removeprefix('www.')
        specs.append(('Source', f'<a href="{esc(c.source)}" target="_blank" rel="noopener noreferrer">{esc(host)}<span aria-hidden="true"> ↗</span><span class="sr-only"> (opens in a new tab)</span></a>'))
    if pic.credit:
        specs.append(('Image', esc(pic.credit)))
    if c.added:
        specs.append(('Added', f'<time datetime="{c.added.isoformat()}">{month(c.added)}</time>'))
    rows = '\n'.join(f'            <div><dt>{label}</dt><dd>{value}</dd></div>' for label, value in specs)

    def step(o: Character | None, rel_: str, label: str) -> str:
        if not o:
            return f'<span class="fc-sheet-step fc-sheet-{rel_}" aria-hidden="true"></span>'
        arrow = '<span aria-hidden="true">← </span>' + label if rel_ == 'prev' else label + '<span aria-hidden="true"> →</span>'
        return (f'<a class="fc-sheet-step fc-sheet-{rel_}" href="{up}{o.slug}/" rel="{rel_}" data-slug="{o.slug}">'
                f'<span class="fc-label">{arrow}</span><span class="fc-sheet-step-title">No. {o.number} {esc(o.title)}</span></a>')

    description = clip(f'{c.summary} No. {c.number} in Familiar Characters, a collection by 2D1.', 200)
    if len(description) > 160:
        description = clip(c.summary, 160)
    data = [{
        '@context': 'https://schema.org', '@type': 'Article', 'headline': c.title, 'description': c.summary,
        'url': c.url, 'mainEntityOfPage': c.url, 'image': [f'{SITE}/img/characters/{pic.variants[-1][1]}'],
        'author': {'@type': 'Organization', 'name': '2D1', 'url': f'{SITE}/'},
        'publisher': {'@type': 'Organization', 'name': '2D1', 'url': f'{SITE}/', 'logo': f'{SITE}/img/brand/logo_red.svg'},
        'isPartOf': {'@type': 'CollectionPage', 'name': 'Familiar Characters', 'url': INDEX_URL},
        'about': {'@type': 'Thing', 'name': c.title, **({'url': c.source} if c.source else {})},
        'position': int(c.number),
        **({'datePublished': c.added.isoformat()} if c.added else {}),
        **({'keywords': ', '.join(c.tags)} if c.tags else {}),
    }, {
        '@context': 'https://schema.org', '@type': 'BreadcrumbList', 'itemListElement': [
            {'@type': 'ListItem', 'position': 1, 'name': '2D1', 'item': f'{SITE}/'},
            {'@type': 'ListItem', 'position': 2, 'name': 'Familiar Characters', 'item': INDEX_URL},
            {'@type': 'ListItem', 'position': 3, 'name': c.title, 'item': c.url}]},
    ]
    top = head(root=root, title=f'{c.title} — Familiar Characters — 2D1', description=description, canonical=c.url,
               robots='noindex, follow' if c.placeholder else 'index, follow', og_type='article',
               og_title=f'{c.title} — Familiar Characters', image=f'{SITE}/img/characters/share/{c.share}',
               image_alt=f'No. {c.number}, {c.title}, in Familiar Characters by 2D1.', data=data, bar=False)
    return f'''{top}
<body class="fc-page fc-sheet-page">
{MARK}
  <main id="main" class="fc-sheet" data-slug="{c.slug}" data-no="{c.number}">
    <div class="fc-sheet-top">
      <a class="fc-sheet-index" href="{up}">Familiar Characters</a>
      <a class="fc-sheet-logo" href="{root}" aria-label="2D1, home">{logo_svg}</a>
      <a class="fc-sheet-close" href="{up}" data-close><span class="fc-sheet-close-label">Close</span><span class="contact-x" aria-hidden="true"></span></a>
    </div>
    <article class="fc-sheet-main" aria-labelledby="fc-sheet-title">
      <figure class="fc-sheet-figure"><img class="fc-sheet-img" src="{fallback(pic, root, 1200)}" srcset="{srcset(pic, root)}" sizes="(min-width: 900px) 56vw, 100vw" width="{pic.width}" height="{pic.height}" alt="{esc(smart(pic.alt))}" fetchpriority="high" decoding="async" style="{picture_style(pic)}"></figure>
      <div class="fc-sheet-text">
        <p class="fc-entry-meta"><span class="sec-idx fc-entry-no"><span class="sr-only">No. </span>{c.number}</span>{"".join(f'<span class="fc-entry-class">{esc(v)}</span>' for v in classification)}</p>
        <h1 class="fc-entry-title" id="fc-sheet-title" tabindex="-1">{esc(c.title)}</h1>
        <p class="fc-entry-by">{by}</p>
        <div class="fc-note">
{note}
        </div>
        <section class="fc-specs" aria-labelledby="fc-specs-title">
          <h2 class="fc-label" id="fc-specs-title">Details</h2>
          <dl>
{rows}
          </dl>
        </section>
      </div>
    </article>
    <nav class="fc-sheet-nav" aria-label="Previous and next Characters">
      {step(before, 'prev', 'Previous')}
      {step(after, 'next', 'Next')}
    </nav>
  </main>
</body>
</html>
'''


# Writing ----------------------------------------------------------------------------------

def write(path: Path, text: str) -> bool:
    if path.exists() and path.read_text(encoding='utf-8') == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')
    return True


def update_sitemap(chars: list, placeholders: bool) -> None:
    path = ROOT / 'sitemap.xml'
    text = path.read_text(encoding='utf-8')
    urls = [] if placeholders else [(INDEX_URL, None)]   # the index waits until every placeholder is gone
    urls += [(c.url, c.added) for c in chars if not c.placeholder]
    start, end = '<!-- familiar-characters -->', '<!-- /familiar-characters -->'
    block = start + ''.join(f'<url><loc>{u}</loc>{f"<lastmod>{d.isoformat()}</lastmod>" if d else ""}</url>' for u, d in urls) + end
    if start in text:
        text = re.sub(re.escape(start) + '.*?' + re.escape(end), block, text, flags=re.S)
    elif urls:
        text = text.replace('</urlset>', block + '</urlset>')
    else:
        return
    write(path, text)


def clean(slugs: set, images: set, shares: set) -> list:
    removed = []
    for f in IMG.glob('*.webp'):
        if f.name not in images:
            f.unlink()
            removed.append(rel(f))
    for f in SHARE.glob('*.jpg'):
        if f.name not in shares:
            f.unlink()
            removed.append(rel(f))
    if OUT.is_dir():
        for d in OUT.iterdir():
            page = d / 'index.html'
            if d.is_dir() and d.name not in slugs and page.is_file() and MARK in page.read_text(encoding='utf-8'):
                page.unlink()
                removed.append(rel(page))
                try:
                    d.rmdir()
                except OSError:
                    pass
    return removed


def from_home() -> tuple:
    home = (ROOT / 'index.html').read_text(encoding='utf-8')
    footer = re.search(r'<footer class="footer">.*?</footer>', home, re.S)
    mark = re.search(r'<svg class="logo-mark".*?</svg>', home, re.S)
    if not footer or not mark:
        raise BuildError('index.html: could not find the footer (<footer class="footer">) or the logo (<svg class="logo-mark">)')
    footer = re.sub(r'\n {6}', '\n  ', footer.group(0))
    return footer, mark.group(0)


def main() -> None:
    parser = argparse.ArgumentParser(description='Build the Familiar Characters pages from _familiar-characters/.')
    parser.add_argument('--check', action='store_true', help='check the content without writing anything')
    args = parser.parse_args()

    errors, warnings = [], []
    settings = load_settings(errors)
    chars = load_characters(settings, errors, warnings) if settings else []
    if not errors and not chars:
        errors.append('_familiar-characters/characters/ has no Characters yet')
    for w in warnings:
        print(f'  note: {w}')
    if errors:
        print('Familiar Characters: nothing was built.\n' + '\n'.join(f'  ✕ {e}' for e in errors), file=sys.stderr)
        sys.exit(1)
    placeholders = [c for c in chars if c.placeholder]
    if args.check:
        print(f'Familiar Characters: {len(chars)} Characters check out ({len(placeholders)} placeholders).')
        return

    try:
        footer, logo_svg = from_home()
    except BuildError as e:
        sys.exit(f'Familiar Characters: {e}')
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    IMG.mkdir(parents=True, exist_ok=True)
    SHARE.mkdir(parents=True, exist_ok=True)
    images, shares = set(), set()
    for c in chars:
        try:
            prepare(c.picture, c, cache, images)
        except OSError as e:
            errors.append(f'{rel(c.path)}: could not read {c.picture.file} ({e})')
    if errors:
        print('Familiar Characters: nothing was built.\n' + '\n'.join(f'  ✕ {e}' for e in errors), file=sys.stderr)
        sys.exit(1)
    CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True))

    chars.sort(key=lambda c: int(c.number), reverse=settings['order'] == 'newest')
    fonts = {'mono18': ImageFont.truetype(str(MONO), 18), 'mono20': ImageFont.truetype(str(MONO), 20),
             'mono22': ImageFont.truetype(str(MONO), 22), 'sans26': ImageFont.truetype(str(FONT), 26),
             'sans28': ImageFont.truetype(str(FONT), 28)}
    for c in chars:
        share_character(c, fonts, shares)
    collection_share = share_collection(chars, settings, fonts, shares)

    changed = write(OUT / 'index.html', index_page(chars, settings, collection_share, footer, logo_svg))
    for i, c in enumerate(chars):   # previous and next follow the index's order
        before = chars[i - 1] if i > 0 else None
        after = chars[i + 1] if i + 1 < len(chars) else None
        changed |= write(OUT / c.slug / 'index.html', sheet_page(c, before, after, logo_svg))
    removed = clean({c.slug for c in chars}, images, shares)
    update_sitemap(chars, bool(placeholders))

    print(f'Familiar Characters: {len(chars)} Character{"" if len(chars) == 1 else "s"} → familiar-characters/ ({"updated" if changed else "no page changes"}).')
    if removed:
        print(f'  removed {len(removed)} file{"" if len(removed) == 1 else "s"} no longer used' + (': ' + ', '.join(removed) if len(removed) <= 6 else ''))
    if placeholders:
        print(f'  {len(placeholders)} placeholder{"s" if len(placeholders) > 1 else ""} (noindex, not in the sitemap): '
              + ', '.join(c.number for c in sorted(placeholders, key=lambda c: c.number)))


if __name__ == '__main__':
    main()
