"""Package the current site for a separate, non-indexed hosted preview.

No dependencies. Does not commit, upload, change DNS, or publish anything.
"""
from pathlib import Path
import re
import shutil

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'dist'
MARKER = OUTPUT / '.2d1-preview-build'
PAGES = ('index.html', 'about/index.html', 'ja/index.html', 'ja/about/index.html')
ASSETS = ('css', 'js', 'img', 'fonts')
EXTENSIONS = {'.css', '.js', '.svg', '.png', '.jpg', '.jpeg', '.webp', '.gif',
              '.ico', '.avif', '.woff', '.woff2', '.eot', '.ttf', '.otf', '.txt', '.md'}


def build():
    if OUTPUT.exists():
        if OUTPUT.is_symlink() or not MARKER.is_file():
            raise SystemExit('Refusing to replace dist/: it is not a generated 2D1 preview.')
        shutil.rmtree(OUTPUT)
    OUTPUT.mkdir()
    MARKER.write_text('Generated by scripts/build-preview.py. Safe to regenerate.\n')
    for name in PAGES:
        source = ROOT / name
        html = source.read_text()
        html, count = re.subn(r'<meta name="robots" content="[^"]*">',
                             '<meta name="robots" content="noindex, nofollow">', html)
        if count != 1:
            raise SystemExit(f'Expected one robots meta tag in {name}')
        target = OUTPUT / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(html)
    for folder in ASSETS:
        for source in (ROOT / folder).rglob('*'):
            relative = source.relative_to(ROOT)
            if any(part.startswith('.') for part in relative.parts):
                continue
            if source.is_symlink():
                raise SystemExit(f'Refusing to package symlink: {relative}')
            if not source.is_file() or source.suffix.lower() not in EXTENSIONS:
                continue
            target = OUTPUT / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
    (OUTPUT / 'robots.txt').write_text('User-agent: *\nDisallow: /\n')
    (OUTPUT / '_headers').write_text('/*\n  X-Robots-Tag: noindex, nofollow\n  X-Content-Type-Options: nosniff\n')
    files = [p for p in OUTPUT.rglob('*') if p.is_file()]
    print(f'Preview package: {OUTPUT}')
    print(f'{len(files)} files, {sum(p.stat().st_size for p in files) / 1024 / 1024:.1f} MiB')
    print('Only the four active pages and site assets are included. No publication performed.')


if __name__ == '__main__':
    build()
